### ISSUE TITLE
how to run  this project by gradle?

### ISSUE THREAD

**Issue by Yisaer** [ddubson/springboot-flyway-strategy#1]
I want to run this project by gradle in several env like dev or prod but I don't know how.

**Comment by ddubson** [comment]
To enable the different profiles, you will need to specify which active profile to run the Spring Boot app with.

The simplest way to do this is via environment variables

To run in `dev` mode, run:

```
# Linux / MacOS
SPRING_PROFILES_ACTIVE=dev ./gradlew bootRun

# Windows
set SPRING_PROFILES_ACTIVE=dev
gradlew.bat bootRun
```

To run in `prod` mode, run:

```
# Linux / MacOS
SPRING_PROFILES_ACTIVE=prod ./gradlew bootRun

# Windows
set SPRING_PROFILES_ACTIVE=prod
gradlew.bat bootRun
```

Let me know if that works.

**Comment by Yisaer** [comment]
Thx a lot .
